### PR TITLE
[WIP] Add support for non-commutative variables #7

### PR DESCRIPTION
**Pull request by blegat**

### CODE REVIEW

**Comment by peterwittek** [comment]
This is really cool. I am trying it, but I fail on a trivial test. For commutative variables, this gives true:

```julia
@polyvar z w
z*w == w*z
```
But for noncommutative ones, I get a `StackOverflowError`:
```julia
@ncpolyvar x y
x*y == y*x
```

**Comment by blegat** [comment]
Thanks for the test, I will add it :) The implementation is still very much incomplete indeed ! Only monomials have been handled but not terms and polynomials already.

**Comment by peterwittek** [comment]
Perfect. I tried the comparison above, and the expansion of (x*y)^2, and they both work as they should. I am looking forward to more updates.

**Comment by blegat** [comment]
@peterwittek It should be fully working now :) Still missing tests though

**Pull request merged**
